### ISSUE TITLE
Informations related to Personal projects are (maybe) wrong

### ISSUE THREAD

**Issue by storrisi** [italia-opensource/state-of-italian-opensource-reports#1]
I might be wrong but the information in this screenshot are not corresponding to the graph.
It seems that the 46% is actually contributing to their own personal projects.
On the other hand, the 54% (32% + 22%) is not working on their projects.

<img width="473" alt="Screenshot 2024-05-23 alle 10 12 46" src="https://github.com/italia-opensource/state-of-italian-opensource-reports/assets/7654979/300767ad-4f92-4460-af9e-f3f8539c9276">

**Comment by FabrizioCafolla** [comment]
@storrisi I just wanted to let you know that I corrected your reported issue.

In the process, I realized that the first item in the list referring to the question `La tua azienda lavora a progetti open-source?`  was also incorrect because 33% (no) + 31% (no, ma vorrei) + 2% (no, ci stiamo lavorando) = 66% 

If you agree with the new changes I will create a pull request and fix it

<img width="720" alt="Screenshot 2024-05-24 alle 11 20 06" src="https://github.com/italia-opensource/state-of-italian-opensource-reports/assets/13237032/c6c46a5c-65ad-46d9-b90a-f5162a6b959b">

**Comment by storrisi** [comment]
Nice! Seems to be ok now, good job!

**Comment by FabrizioCafolla** [comment]
Done 🎉
